[package]
name = "compilador_banco"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yansi = "0.5"
spinners = "2.0"
human-panic = "1.0"
chrono = "0.4"
which = "4.2"
